services:
    nginx:
        image: nginxinc/nginx-unprivileged
        ports:
            - '8080:80'
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./logs/nginx:/var/log/nginx
            - ./wp:/var/www/html
        user: 1000:1000
        links:
            - wordpress
        restart: always

    mysql:
        image: mariadb
        user: mysql
        ports:
            - '3306:3306'
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=wpdb
            - MYSQL_USER=wpuser
            - MYSQL_PASSWORD=pass
        restart: always

    wordpress:
        image: wordpress:6.7.1-php8.1-fpm
        ports:
            - '9000:9000'
        volumes:
            - ./wp:/var/www/html
            - ./conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        environment:
            WORDPRESS_DB_NAME: wpdb
            WORDPRESS_TABLE_PREFIX: wp_
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: pass
        links:
            - mysql
        depends_on:
            - mysql
        restart: always
    # phpmyadmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64
        ports:
          - '8888:80'
        environment:
          PMA_HOST: mysql
          MYSQL_ROOT_PASSWORD: pass
        # LogIn//  user name   root      password   password
        links:
          - mysql
        depends_on:
          - mysql
        restart: always

